services:
  shop:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
  shop_api_db:
    image: "postgres:14"
    environment:
      POSTGRES_DB: shop_api_db
      POSTGRES_USER: shop_api_user
      POSTGRES_PASSWORD: 12345
    volumes:
      - 'pqdata:/var/lib/postgresql/data'
volumes:
  pqdata:
